name: treehideout
description: 익명성을 보장하는 채팅 앱

publish_to: 'none' # 패키지를 pub.dev에 게시하지 않음

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  socket_io_client: ^2.0.0
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^9.0.0
  uuid: ^3.0.6
  encrypt: ^5.0.1
  pointycastle: ^3.6.2
  intl: ^0.17.0
  device_info_plus: ^9.0.2  # 디바이스 정보를 얻기 위한 패키지
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # 필요한 경우 여기에 assets 추가
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg